### ISSUE TITLE
Méthode find

### ISSUE THREAD

**Issue by PierCase** [maltyxx/orm#7]
J'essaie d'exécuter le code suivant sur CI3 et j'ai l'erreur suivante : 

$model_a = new \gmb\artist_model();
$model_a->find();

Fatal error: Call to undefined method CI_DB_mysqli_driver::find() 

Pourtant le model extend bien l'ORM

**Comment by maltyxx** [comment]
Vous devez utilisé la dernière version de l'ORM v3.3.1, c'est pour cela que ça ne fonctionne pas.

**Comment by PierCase** [comment]
Dans ce cas pouvez vous tagger les derniers fichier car en faisant un composer require ou update on a pas la bonne version.
En effet on a un fichier ORM qui contient la ligne suivante : protected $version = '3.2.12 (20150428)';

essayer de l'installer avec composer et vous verrez qu'il y a un problème,

merci,

**Comment by PierCase** [comment]
Le tag 3.3.1 ne contient pas les fichiers qu'il faut ;)

**Comment by PierCase** [comment]
Le problème vient de là : 
$a_artists = $model_a->like($search_field, $search, "after")->find();

on ne peut pas faire un like puis un find.

merci de réouvrir ce ticket
